INSERT INTO club (id, name, officialname, country, venue_id) VALUES
	('26', 'AFC Bournemouth', 'AFC Bournemouth', 'England', '450'),
	('89', 'Amiens SC', 'Amiens SC', 'France', '484'),
	('35', 'Angers', 'Angers SCO', 'France', '1824'),
	('84', 'Arsenal', 'Arsenal FC', 'England', '372'),
	('63', 'Atalanta', 'Atalanta Bergamasca Calcio', 'Italy', '747'),
	('9', 'Athletic Club', 'Athletic Club Bilbao', 'Spain', '1536'),
	('10', 'Atletico Madrid', 'Club Atletico de Madrid', 'Spain', '1538'),
	('69', 'Augsburg', 'FC Augsburg', 'Germany', '588'),
	('15', 'Barcelona', 'FC Barcelona', 'Spain', '1477'),
	('29', 'Bayer Leverkusen', 'TSV Bayer 04 Leverkusen', 'Germany', '536'),
	('31', 'Bayern Munchen', 'FC Bayern Munchen', 'Germany', '532'),
	('57', 'Benevento', 'Benevento Calcio', 'Italy', '1823'),
	('47', 'Bologna', 'Bologna FC 1909', 'Italy', '776'),
	('40', 'Bordeaux', 'FC Girondins de Bordeaux', 'France', '475'),
	('30', 'Borussia Dortmund', 'BV Borussia 09 Dortmund', 'Germany', '596'),
	('7', 'Borussia M\'gladbach', 'Borussia VfL Monchengladbach', 'Germany', '538'),
	('27', 'Brighton & Hove Albion', 'Brighton & Hove Albion FC', 'England', '349'),
	('39', 'Burnley', 'Burnley FC', 'England', '443'),
	('85', 'Caen', 'Stade Malherbe Caen', 'France', '514'),
	('62', 'Cagliari', 'Cagliari Calcio', 'Italy', '739'),
	('1', 'Celta de Vigo', 'Real Club Celta de Vigo', 'Spain', '1473'),
	('78', 'Chelsea', 'Chelsea FC', 'England', '432'),
	('50', 'Chievo', 'AC Chievo Verona', 'Italy', '763'),
	('90', 'Crotone', 'FC Crotone', 'Italy', '1821'),
	('70', 'Crystal Palace', 'Crystal Palace FC', 'England', '422'),
	('3', 'Deportivo Alaves', 'Deportivo Alaves', 'Spain', '1495'),
	('82', 'Deportivo La Coruna', 'Real Club Deportivo de La Coruna', 'Spain', '1474'),
	('42', 'Dijon', 'Dijon FCO', 'France', '505'),
	('25', 'Eibar', 'SD Eibar', 'Spain', '1505'),
	('74', 'Eintracht Frankfurt', 'Eintracht Frankfurt', 'Germany', '542'),
	('2', 'Espanyol', 'Reial Club Deportiu Espanyol', 'Spain', '1535'),
	('65', 'Everton', 'Everton FC', 'England', '380'),
	('64', 'Fiorentina', 'ACF Fiorentina', 'Italy', '745'),
	('46', 'Freiburg', 'SC Freiburg', 'Germany', '594'),
	('92', 'Genoa', 'Genoa CFC', 'Italy', '762'),
	('6', 'Getafe', 'Getafe Club de Futbol', 'Spain', '1479'),
	('59', 'Girona', 'Girona FC', 'Spain', '1822'),
	('88', 'Guingamp', 'En Avant Guingamp', 'France', '495'),
	('45', 'Hamburger SV', 'Hamburger SV', 'Germany', '615'),
	('41', 'Hannover 96', 'Hannover 96', 'Germany', '564'),
	('91', 'Hellas Verona', 'Hellas Verona FC', 'Italy', '763'),
	('43', 'Hertha BSC', 'Hertha BSC', 'Germany', '580'),
	('61', 'Hoffenheim', 'TSG 1899 Hoffenheim', 'Germany', '544'),
	('8', 'Huddersfield Town', 'Huddersfield Town FC', 'England', '386'),
	('53', 'Internazionale', 'FC Internazionale Milano', 'Italy', '781'),
	('36', 'Juventus', 'Juventus FC', 'Italy', '735'),
	('76', 'Koln', '1. FC Koln', 'Germany', '587'),
	('16', 'Las Palmas', 'UD Las Palmas', 'Spain', '1502'),
	('51', 'Lazio', 'SS Lazio', 'Italy', '766'),
	('17', 'Leganes', 'CD Leganes', 'Spain', '1491'),
	('54', 'Leicester City', 'Leicester City FC', 'England', '391'),
	('4', 'Levante', 'Levante UD', 'Spain', '1480'),
	('73', 'Lille', 'Lille OSC Metropole', 'France', '508'),
	('77', 'Liverpool', 'Liverpool FC', 'England', '350'),
	('72', 'Mainz 05', '1. FSV Mainz 05', 'Germany', '540'),
	('96', 'Malaga', 'Malaga Club de Futbol', 'Spain', '1509'),
	('67', 'Manchester City', 'Manchester City FC', 'England', '373'),
	('79', 'Manchester United', 'Manchester United FC', 'England', '407'),
	('48', 'Metz', 'FC Metz', 'France', '520'),
	('34', 'Milan', 'AC Milan', 'Italy', '781'),
	('71', 'Monaco', 'AS Monaco FC', 'Monaco', '510'),
	('87', 'Montpellier', 'Montpellier HSC', 'France', '494'),
	('21', 'Nantes', 'FC Nantes', 'France', '490'),
	('81', 'Napoli', 'SSC Napoli', 'Italy', '780'),
	('0', 'Newcastle United', 'Newcastle United FC', 'England', '428'),
	('22', 'Nice', 'O.G.C. Nice Cote d\'Azur', 'France', '473'),
	('11', 'Olympique Lyonnais', 'Olympique Lyonnais', 'France', '474'),
	('20', 'Olympique Marseille', 'Olympique de Marseille', 'France', '477'),
	('12', 'PSG', 'Paris Saint-Germain FC', 'France', '478'),
	('83', 'RB Leipzig', 'Rasen Ballsport Leipzig', 'Germany', '585'),
	('93', 'Real Betis', 'Real Betis Balompie', 'Spain', '1486'),
	('14', 'Real Madrid', 'Real Madrid Club de Futbol', 'Spain', '1522'),
	('94', 'Real Sociedad', 'Real Sociedad de Futbol', 'Spain', '1485'),
	('23', 'Rennes', 'Stade Rennais FC', 'France', '479'),
	('37', 'Roma', 'AS Roma', 'Italy', '766'),
	('58', 'Saint-Etienne', 'AS Saint-Etienne', 'France', '506'),
	('49', 'Sampdoria', 'UC Sampdoria', 'Italy', '762'),
	('38', 'Sassuolo', 'US Sassuolo Calcio', 'Italy', '738'),
	('33', 'Schalke 04', 'FC Schalke 04', 'Germany', '612'),
	('95', 'Sevilla', 'Sevilla FC', 'Spain', '1534'),
	('75', 'Southampton', 'Southampton FC', 'England', '429'),
	('18', 'SPAL', 'Societa Polisportiva Ars et Labor 2013', 'Italy', '768'),
	('56', 'Stoke City', 'Stoke City FC', 'England', '353'),
	('24', 'Strasbourg', 'RC Strasbourg Alsace', 'France', '493'),
	('32', 'Stuttgart', 'VfB Stuttgart 1893', 'Germany', '558'),
	('19', 'Swansea City', 'Swansea City AFC', 'Wales', '1817'),
	('80', 'Torino', 'Torino FC', 'Italy', '752'),
	('68', 'Tottenham Hotspur', 'Tottenham Hotspur FC', 'England', '451'),
	('86', 'Toulouse', 'Toulouse FC', 'France', '524'),
	('5', 'Troyes', 'Esperance Sportive Troyes Aube Champagne', 'France', '487'),
	('52', 'Udinese', 'Udinese Calcio', 'Italy', '737'),
	('13', 'Valencia', 'Valencia Club de Futbol', 'Spain', '1512'),
	('97', 'Villarreal', 'Villarreal Club de Futbol', 'Spain', '1492'),
	('60', 'Watford', 'Watford FC', 'England', '446'),
	('28', 'Werder Bremen', 'SV Werder Bremen', 'Germany', '621'),
	('66', 'West Bromwich Albion', 'West Bromwich Albion FC', 'England', '437'),
	('55', 'West Ham United', 'West Ham United FC', 'England', '394'),
	('44', 'Wolfsburg', 'VfL Wolfsburg', 'Germany', '613');
