services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart:
      always
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app 

  db:
    image: postgres:latest
    env_file:
      - .env
    restart:
      always      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      retries: 5
      timeout: 3s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv_files:/data/csv_files
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
