services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./${INIT_SQL}:/docker-entrypoint-initdb.d/${INIT_SQL}
      - ./csv_files:/data/csv_files
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"